services:
  ui:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5173:5173" 
    volumes:
      - ./app:/app/app
      - ./server:/app/server
      - ./public:/app/public
      - ./index.html:/app/index.html
      - ./tsconfig.json:/app/tsconfig.json
      - ./nuxt.config.ts:/app/nuxt.config.ts
    networks:
      - intranet
    depends_on:
      - kratos
      - hydra
