#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE DATABASE kratos;
    CREATE DATABASE hydra;
    GRANT ALL PRIVILEGES ON DATABASE kratos TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE hydra TO $POSTGRES_USER;
EOSQL