services:
  kratos-migrate:
    image: oryd/kratos:v1.2.0
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true&mode=rwc
    volumes:
      - type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./cfg/ory/kratos
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    networks:
      - intranet

  # kratos-selfservice-ui-node:
  #   image: oryd/kratos-selfservice-ui-node:v1.2.0
  #   environment:
  #     - KRATOS_PUBLIC_URL=http://kratos:4433/
  #     - KRATOS_BROWSER_URL=http://127.0.0.1:4433/
  #     - COOKIE_SECRET=${UI_COOKIE_SECRET}
  #     - CSRF_COOKIE_NAME=ory_csrf_ui
  #     - CSRF_COOKIE_SECRET=${UI_CSRF_COOKIE_SECRET}
  #   networks:
  #     - intranet
  #   restart: on-failure

  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v1.2.0
    ports:
      - "4433:4433" # public
      - "4434:4434" # admin
    restart: unless-stopped
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
      - LOG_LEVEL=trace
      - SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_0_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - SELFSERVICE_METHODS_OIDC_CONFIG_PROVIDERS_0_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - SECRETS_COOKIE=${KRATOS_SECRETS_COOKIE}
      - SECRETS_CIPHER=${KRATOS_SECRETS_CIPHER}
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - type: volume
        source: kratos-sqlite
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./cfg/ory/kratos
        target: /etc/config/kratos
    networks:
      - intranet

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - "4436:4436"
      - "4437:4437"
    networks:
      - intranet
networks:
  intranet:
volumes:
  kratos-sqlite:
